custom_authentication/config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  post 'login' => 'users#access'

  resources :users, only: [:new, :create] do
    collection do
      get 'login'
      delete 'logout'
    end
  end
end

custom_authentication/app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_digest

  validates :username, :email, :password_digest, presence: true
  validates :email, :password_digest, uniqueness: true
  validates :password, length: { minimum: 6 }

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_digest = User.new_token
    update_attribute(:remember_token, User.digest(remember_digest))
  end

  def authenticated?(remember_digest)
    BCrypt::Password.new(remember_token).is_password?(remember_digest)
  end

  def forget
    update_attribute(:remember_token, nil)
  end
end

custom_authentication/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  helper_method :logged_in?
  


  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= if (user_id = session[:user_id])
      User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_digest])
        log_in user
        user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_digest] = user.remember_digest
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_digest)
  end

  def logged_in_user
    unless logged_in?
      redirect_to login_users_path, alert: "Please log in."
    end
  end
end

custom_authentication/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :logged_in_user
  def index; end
end

custom_authentication/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path, notice: "User has been signed up"
    else
      flash.now[:alert] = [@user.errors.full_messages].join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def login; end

  def access
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      log_in user
      params[:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_path, notice: "You have successfully logged in ... "
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render :login, status: :unprocessable_entity
    end
  end

  def logout
    log_out
    redirect_to root_path, notice: "You have successfully logged out ... "
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

custom_authentication/app/helpers/homes_helper.rb
module HomesHelper
end

custom_authentication/app/helpers/users_helper.rb
module UsersHelper
end

custom_authentication/app/views/homes/index.html.erb
<% if logged_in? %>
  <h1>Hello <%= current_user.username %> welcome to the site !</h1>
  <%= button_to "Log out", logout_users_path, method: :delete, class: "btn btn-danger" %>
<% else %>
  <h1>Welcome home!</h1>
  <div class="btn btn-info"><%= link_to "Log in", login_users_path, class: "btn btn-info" %></div>
<% end %>

custom_authentication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomAuthentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

custom_authentication/app/views/users/login.html.erb
<div class="container">
  <h2 class="badge bg-primary text-wrap" style="width: auto; height: 30px; font-size: 20px;">Log In</h2>
  <div class="card" >
      <%= form_with url: login_path, method: :post do |form| %>
      <div class="card" >
        <%= form.label :email, class: "form-label" %>
        <%= form.email_field :email, class: "form-control", required: true, type: :email %><br>
      </div>

      <div class="card">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control", required: true, minlength: 6 %><br>
      </div>

      <%= form.label :remember_me, class: "form-label" %>
      <%= form.check_box :remember_me %><br>

      <%= form.submit "login", class: "btn btn-info" %>
      <% end %>
  </div>
  <p>Don't have an account? <%= link_to "sign up!", new_user_path %></p>
</div>

custom_authentication/app/views/users/new.html.erb
<div class="container" >
  <div class="card">
    <h1 class="badge bg-primary text-wrap" style="width: auto; height: 30px; font-size: 20px;">Signup!</h1>
    <%= form_with model: @user do |form| %>
      <div class="card">
        <%= form.label :username, class: "form-label" %>
        <%= form.text_field :username, class: "form-control"  %><br>
        <% @user.errors.full_messages_for(:username).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div class="card">
        <%= form.label :email, class: "form-label" %>
        <%= form.email_field :email, class: "form-control"  %><br>
          <% @user.errors.full_messages_for(:email).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div class="card">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control"  %><br>
          <% @user.errors.full_messages_for(:password).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

    <%= form.submit %>
  <% end %>
  <p>Already have an account? <%= link_to "log in", login_users_path %></p>
  </div>
</div>